export type Bounty = {
  id: number;
  bounty_id: number;
  title: string;
  date: string;
  bounty_created: string;
  paid_date: string;
  dtgp: number;
  assignee: string;
  assigneeImage: string;
  provider: string;
  providerImage: string;
  organization_name: string;
  organizationImage: string;
  status: string;
  assignee_alias: string;
  paid: boolean;
  owner_id?: string;
  owner_img?: string;
  owner_unique_name?: string;
  owner_alias?: string;
  owner_pubkey?: string;
};
