/* eslint-disable no-unused-vars */
export enum MOCK_ENVIRONMENT_HOOKS {
  BOUNTY_DATA = 'BOUNTY_DATA',
  BOUNTY_ROES = 'BOUNTY_ROES',
  DROPDOWN_ORGANIZATION_DATA = 'DROPDOWN_ORGANIZATION_DATA',
  ORGANIZATION_DATA = 'ORGANIZATION_DATA',
  SELF_PROFILE_STORE = 'SELF_PROFILE_STORE',
  USD_TO_SAT_EXCHANGE_RATE = 'USD_TO_SAT_EXCHANGE_RATE'
}
