name: Docker build on push (master)
env:
  DOCKER_CLI_EXPERIMENTAL: enabled

on:
  push:
    branch:
      - master

# https://docs.github.com/en/actions/learn-github-actions/expressions
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build and push Tribes image (master)
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out from Git
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Docker buildx action
        uses: crazy-max/ghaction-docker-buildx@v1
        id: buildx
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Run Docker buildx
        run: |
          docker buildx build \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --platform linux/amd64,linux/arm/v7 \
          --tag "${{ secrets.DOCKER_HUB_USER }}/sphinx-tribes-frontend:master" \
          --output "type=registry" ./



